import { expect, test, type Page } from "@playwright/test"
import fs from "node:fs/promises"
import path from "node:path"

const screenshotDir = process.env.ASTERIA_BROWSER_QA_DIR || "/tmp/asteria-browser-qa"
const acceptanceDir = process.env.ASTERIA_ACCEPTANCE_SCREENSHOT_DIR || path.resolve("results/asteria_v2_rc6_acceptance/screenshots")

function relationIdSelector(relationId: string) {
  return `[data-relation-id="${relationId}"]`
}

async function assertNoLegacyStartup(page: Page) {
  for (const forbidden of ["Choose a starting version", "Use shared version", "New from scratch"]) {
    await expect(page.getByText(forbidden, { exact: false })).toHaveCount(0)
  }
}

async function assertNoLegacyToolbar(page: Page) {
  for (const forbiddenButton of ["Move", "Edit", "Zoom", "New block", "Equation", "Fit", "Clean"]) {
    await expect(page.getByRole("button", { name: new RegExp(`^${forbiddenButton}$`, "i") })).toHaveCount(0)
  }
}

test.beforeEach(async ({ page }) => {
  const consoleIssues: string[] = []
  ;(page as unknown as { __asteriaConsoleIssues: string[] }).__asteriaConsoleIssues = consoleIssues
  page.on("console", (message) => {
    if (message.type() === "error") consoleIssues.push(message.text())
  })
  page.on("pageerror", (error) => consoleIssues.push(error.message))
  await page.addInitScript(() => {
    window.localStorage.removeItem("asteria-v2-rc-view-state")
    window.localStorage.setItem("asteria-theme", "dark")
  })
  await page.goto("/")
  await expect(page.getByTestId("asteria-v2-root-shell")).toBeVisible()
  await expect(page.getByTestId("asteria-v2-topbar")).toBeVisible()
  await expect(page.getByText("2.0.0-rc.6")).toBeVisible()
  await expect(page.getByTestId("current-project")).toContainText("Project: CAT-TRACE")
  await expect(page.getByTestId("current-view")).toContainText("Architecture")
  await expect(page.getByTestId("current-model")).toContainText("CAT-TRACE Frozen V2")
  await expect(page.getByTestId("topbar-model-selector")).toHaveValue("cat-trace-frozen-v2")
  await expect(page.getByTestId("right-panel-title")).toContainText("Architecture")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-detail-level", "overview")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-trace-enabled", "false")
  await expect(page.getByTestId("detail-overview")).toHaveAttribute("data-asteria-selected", "true")
  await expect(page.getByTestId("upstream-count")).toHaveCount(0)
  await expect(page.getByTestId("downstream-count")).toHaveCount(0)
  await expect(page.getByTestId("architecture-reference-panel")).toBeVisible()
  await assertNoLegacyStartup(page)
  await assertNoLegacyToolbar(page)
})

test.afterEach(async ({ page }) => {
  const consoleIssues = ((page as unknown as { __asteriaConsoleIssues?: string[] }).__asteriaConsoleIssues || []).filter((issue) => !issue.includes("Failed to load resource: the server responded with a status of 404"))
  expect(consoleIssues).toEqual([])
})

test("G05 Architecture browser QA covers canonical trace, diff, export, and 2.0 local save/restore", async ({ page }) => {
  await fs.mkdir(screenshotDir, { recursive: true })
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-active-model", "cat-trace-frozen-v2")
  await expect(page.getByTestId("selected-symbol-math").locator(".katex")).toBeVisible()
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-betaU_gh").locator(".katex")).toBeVisible()
  await expect(page.getByTestId("architecture-workspace-stage")).not.toContainText("\\beta")
  const overviewCount = Number(await page.getByTestId("architecture-projection-canvas").getAttribute("data-projected-entity-count"))
  await page.getByTestId("detail-full-model").click()
  const fullCount = Number(await page.getByTestId("architecture-projection-canvas").getAttribute("data-projected-entity-count"))
  expect(fullCount).toBeGreaterThan(overviewCount)
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-Gamma")).toBeVisible()
  await page.getByTestId("detail-overview").click()
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-Gamma")).toHaveCount(0)
  await page.getByTestId("symbol-betaU_gh").click()
  await expect(page.getByTestId("symbol-inspector")).toContainText("Open-tail slope")
  await expect(page.getByTestId("architecture-reference-panel")).toContainText("beta^U_gh = nu + a_g + v^U_gh")
  await expect(page.getByTestId("trace-lists")).toContainText("Active trace is off")

  await page.getByTestId("enable-trace").click()
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-trace-enabled", "true")
  await page.getByTestId("trace-mode").selectOption("recursive")
  await page.getByTestId("trace-direction").selectOption("both")
  await page.getByTestId("trace-depth").fill("3")
  await expect(page.getByTestId("trace-lists")).toContainText("Shared environmental-response vector")
  await expect(page.getByTestId("trace-lists")).toContainText("Open-tail latent score")

  await page.getByTestId("symbol-p_g").click()
  await expect(page.getByTestId("architecture-reference-panel")).toContainText("not true unknown species count")
  await page.getByTestId("layer-focus").selectOption("parameterization")
  await expect(page.getByTestId("architecture-outline")).toContainText("Parameterization")
  await expect(page.getByTestId("semantic-diff")).toContainText("Finite catalogue")
  await expect(page.getByTestId("semantic-diff")).toContainText("Added")
  await expect(page.getByTestId("semantic-diff")).toContainText("Preserved")
  await page.getByTestId("clear-architecture-selection").click()
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-detail-level", "overview")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-trace-enabled", "false")
  await expect(page.getByTestId("trace-mode")).toHaveValue("direct")
  await expect(page.getByTestId("trace-direction")).toHaveValue("both")
  await expect(page.getByTestId("trace-depth")).toHaveValue("2")
  await expect(page.getByTestId("layer-focus")).toHaveValue("all")
  await expect(page.getByTestId("symbol-inspector")).toContainText("Open-tail slope")
  await expect(page.getByTestId("upstream-count")).toHaveCount(0)
  await expect(page.locator('[data-trace-active="true"]')).toHaveCount(0)

  await page.getByTestId("advanced-export-validation").click()
  await page.getByTestId("export-json").click()
  await expect(page.getByTestId("architecture-export-preview")).toContainText("\"schemaVersion\"")
  await expect(page.getByTestId("architecture-export-preview")).toContainText("\"validationWarnings\"")
  await page.getByTestId("export-markdown").click()
  await expect(page.getByTestId("architecture-export-preview")).toContainText("# CAT-TRACE Frozen V2")

  await page.getByTestId("save-view-state").click()
  await expect(page.getByTestId("architecture-action-status")).toContainText("saved")
  await page.getByTestId("model-original-trace").click()
  await expect(page.getByTestId("symbol-inspector")).toContainText("Observed occurrence")
  await page.getByTestId("restore-view-state").click()
  await expect(page.getByTestId("architecture-action-status")).toContainText("restored")
  await expect(page.getByTestId("symbol-inspector")).toContainText("Open-tail slope")

  await page.getByTestId("architecture-reference-panel").evaluate((element) => {
    element.scrollTop = 0
  })
  await page.screenshot({ path: path.join(screenshotDir, "g05-architecture-desktop.png"), fullPage: false })
  await page.setViewportSize({ width: 1366, height: 768 })
  await expect(page.getByTestId("architecture-reference-panel")).toBeVisible()
  await expect(page.getByTestId("symbol-inspector")).toBeVisible()
  await page.screenshot({ path: path.join(screenshotDir, "g05-architecture-laptop.png"), fullPage: false })
})

test("G06 multi-view browser QA covers Lineage, Evidence, cross-view links, search, and theme", async ({ page }) => {
  await fs.mkdir(screenshotDir, { recursive: true })
  await page.getByTestId("view-lineage").click()
  await expect(page.getByTestId("current-view")).toContainText("Lineage")
  await expect(page.getByTestId("right-panel-title")).toContainText("Lineage")
  await expect(page.getByTestId("active-view-help")).toContainText("Lineage answers")
  await expect(page.getByTestId("current-model")).toHaveCount(0)
  await expect(page.getByTestId("architecture-workspace-stage")).toBeVisible()
  await expect(page.getByTestId("central-lineage-canvas")).toContainText("CAT-TRACE Frozen V2")
  await expect(page.getByTestId("central-lineage-canvas")).toContainText("TRACE / Infinite JSDM")
  await expect(page.getByTestId("central-lineage-canvas")).toContainText("HMSC framework")
  await expect(page.getByTestId("central-lineage-canvas")).toContainText("bigMVP")
  await expect(page.getByTestId("central-lineage-canvas")).toContainText("Sparse Bayesian infinite factor / MGP")
  await expect(page.getByTestId("method-inspector")).toContainText("CAT-TRACE Frozen V2")
  await expect(page.getByTestId("context-relations")).toContainText("extends")
  await expect(page.getByTestId("context-relations")).toContainText("borrows interpretation from")
  await page.screenshot({ path: path.join(screenshotDir, "g06-lineage-desktop.png"), fullPage: false })

  await page.getByTestId("context-open-evidence").click()
  await expect(page.getByTestId("current-view")).toContainText("Evidence")
  await expect(page.getByTestId("right-panel-title")).toContainText("Evidence")
  await expect(page.getByTestId("active-view-help")).toContainText("Evidence answers")
  await expect(page.getByTestId("central-evidence-canvas")).toContainText("Open-tail response decomposition is explicit")
  await expect(page.getByTestId("view-evidence")).toHaveClass(/segmented-button-active/)
  await expect(page.getByTestId("workspace-view-evidence")).toHaveClass(/architecture-workspace-rail-active/)
  await expect(page.getByTestId("claim-inspector")).toContainText("Open-tail response decomposition is explicit")
  await expect(page.getByTestId("context-relations")).toContainText("validates implementation")
  await expect(page.getByTestId("closure-gaps")).toContainText("Marked discovery theorem")
  await expect(page.getByTestId("closure-gaps")).toContainText("Pending")
  await expect(page.getByTestId("closure-gaps")).toContainText("open gap")
  await page.screenshot({ path: path.join(screenshotDir, "g06-multiview-desktop.png"), fullPage: false })

  await page.getByTestId("architecture-search-scope").selectOption("all")
  await page.getByTestId("architecture-search-input").fill("Finland")
  await expect(page.getByTestId("architecture-search-results")).toContainText("Finland fungi")
  await expect(page.getByTestId("architecture-search-results")).toContainText("Evidence / dataset")
  await page.getByTestId("search-result-finland").click()
  await expect(page.getByTestId("current-view")).toContainText("Evidence")
  await expect(page.getByTestId("right-panel-title")).toContainText("Evidence")
  await expect(page.getByTestId("claim-inspector")).toContainText("Finland fungi")
  await expect(page.getByTestId("architecture-reference-panel")).toContainText("Dataset Inspector")
  await expect(page.getByTestId("researcher-status")).toContainText("Pending")

  await page.getByTestId("architecture-search-scope").selectOption("all")
  await page.getByTestId("architecture-search-input").fill("Marked discovery")
  await page.getByTestId("search-result-marked-discovery").click()
  await expect(page.getByTestId("architecture-reference-panel")).toContainText("Claim Inspector")
  await expect(page.getByTestId("researcher-status")).toContainText("Pending")

  await page.getByTestId("architecture-search-scope").selectOption("all")
  await page.getByTestId("architecture-search-input").fill("HMSC")
  await expect(page.getByTestId("architecture-search-results")).toContainText("HMSC framework")
  await expect(page.getByTestId("architecture-search-results")).toContainText("Lineage / method")
  await page.getByTestId("search-result-hmsc").click()
  await expect(page.getByTestId("current-view")).toContainText("Lineage")
  await expect(page.getByTestId("right-panel-title")).toContainText("Lineage")
  await expect(page.getByTestId("method-inspector")).toContainText("HMSC framework")

  await page.getByTestId("architecture-search-input").fill("zzzz-no-result")
  await expect(page.getByTestId("architecture-search-empty")).toContainText("No results")

  await page.getByTestId("view-lineage").click()
  await page.getByTestId("architecture-search-input").fill("HMSC")
  await page.getByTestId("save-view-state").click()
  await page.getByTestId("view-evidence").click()
  await page.getByTestId("restore-view-state").click()
  await expect(page.getByTestId("current-view")).toContainText("Lineage")
  await expect(page.getByTestId("architecture-search-input")).toHaveValue("")

  await page.getByTestId("topbar-toggle-theme").click()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light")

  await page.setViewportSize({ width: 1366, height: 768 })
  await page.getByTestId("view-evidence").click()
  await expect(page.getByTestId("claim-inspector")).toBeVisible()
  await page.screenshot({ path: path.join(screenshotDir, "g06-evidence-laptop.png"), fullPage: false })
})

test("RC6 acceptance covers direct 2.0 entry, selectors, views, trace-edge truth, and committed screenshots", async ({ page }) => {
  await fs.mkdir(acceptanceDir, { recursive: true })
  await assertNoLegacyStartup(page)
  await assertNoLegacyToolbar(page)

  await expect(page.getByTestId("model-cat-trace-frozen-v2")).toHaveAttribute("data-asteria-selected", "true")
  await expect(page.getByTestId("view-architecture")).toHaveAttribute("data-asteria-selected", "true")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-active-model", "cat-trace-frozen-v2")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-detail-level", "overview")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-trace-enabled", "false")
  await expect(page.getByTestId("central-model-status")).toContainText("CAT-TRACE Frozen V2")
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-betaU_gh")).toBeVisible()
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-c_f")).toBeVisible()
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-mathcal_U")).toBeVisible()
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-betaU_gh")).toHaveAttribute("data-projection-x", "985")
  await expect(page.getByTestId("projection-node-entity-cat-trace-frozen-v2-betaU_gh")).toHaveAttribute("data-diff-status", "modified_definition")
  await page.screenshot({ path: path.join(acceptanceDir, "architecture-cat-trace-dark.png"), fullPage: false })
  await page.setViewportSize({ width: 1536, height: 864 })
  await page.getByTestId("topbar-toggle-theme").click()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light")
  await page.screenshot({ path: path.join(acceptanceDir, "architecture-cat-trace-light-1536.png"), fullPage: false })
  await page.getByTestId("topbar-toggle-theme").click()
  await page.setViewportSize({ width: 1366, height: 768 })
  await expect(page.getByTestId("architecture-projection-canvas")).toBeVisible()
  await expect(page.getByTestId("right-panel-title")).toContainText("Architecture")
  await page.screenshot({ path: path.join(acceptanceDir, "architecture-cat-trace-dark-1366.png"), fullPage: false })

  await page.getByTestId("model-original-trace").click()
  await expect(page.getByTestId("current-model")).toContainText("Original TRACE")
  await expect(page.getByTestId("model-original-trace")).toHaveAttribute("data-asteria-selected", "true")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-active-model", "original-trace")
  await expect(page.getByTestId("central-model-status")).toContainText("Original TRACE")
  await expect(page.getByTestId("projection-node-entity-original-trace-y_ij")).toBeVisible()
  await expect(page.getByTestId("projection-node-entity-original-trace-z_ij")).toBeVisible()
  await expect(page.getByTestId("projection-node-entity-original-trace-beta_j")).toBeVisible()
  await expect(page.locator('[data-entity-id="entity:cat-trace-frozen-v2:betaU_gh"]')).toHaveCount(0)
  await expect(page.locator(relationIdSelector("relation:original-trace:0:z_ij:y_ij"))).toHaveAttribute("data-relation-type", "generates")
  await page.screenshot({ path: path.join(acceptanceDir, "architecture-original-trace-dark.png"), fullPage: false })

  await page.getByTestId("model-cat-trace-frozen-v2").click()
  await page.getByTestId("symbol-betaU_gh").click()
  await page.getByTestId("enable-trace").click()
  await page.getByTestId("trace-mode").selectOption("direct")
  await page.getByTestId("trace-direction").selectOption("upstream")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:11:nu:betaU_gh"))).toHaveAttribute("data-trace-active", "true")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:11:nu:betaU_gh"))).toHaveAttribute("data-trace-role", "upstream")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:12:a_g:betaU_gh"))).toHaveAttribute("data-trace-active", "true")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:13:vU_gh:betaU_gh"))).toHaveAttribute("data-trace-active", "true")
  await page.getByTestId("trace-direction").selectOption("downstream")
  await page.getByTestId("trace-mode").selectOption("recursive")
  await page.getByTestId("trace-depth").fill("3")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:9:betaU_gh:zU_igh"))).toHaveAttribute("data-trace-active", "true")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:9:betaU_gh:zU_igh"))).toHaveAttribute("data-trace-role", "downstream")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:4:zU_igh:yU_igh"))).toHaveAttribute("data-trace-active", "true")
  await expect(page.locator(relationIdSelector("relation:cat-trace-frozen-v2:31:yU_igh:richness_targets"))).toHaveAttribute("data-trace-active", "true")
  await page.screenshot({ path: path.join(acceptanceDir, "architecture-trace-focus.png"), fullPage: false })

  await page.getByTestId("symbol-p_g").click()
  await page.getByTestId("trace-mode").selectOption("recursive")
  await page.getByTestId("trace-direction").selectOption("both")
  await page.getByTestId("trace-depth").fill("3")
  await expect(page.getByTestId("upstream-count")).toContainText("Upstream 0")
  const bothDownstream = await page.getByTestId("downstream-count").textContent()
  await page.getByTestId("trace-direction").selectOption("upstream")
  await expect(page.getByTestId("upstream-count")).toContainText("Upstream 0")
  await expect(page.getByTestId("downstream-count")).toContainText("Downstream 0")
  await page.getByTestId("trace-direction").selectOption("downstream")
  await expect(page.getByTestId("downstream-count")).toContainText(bothDownstream || "")

  await page.getByTestId("projection-node-entity-cat-trace-frozen-v2-mathcal_U").click()
  await expect(page.getByTestId("selected-relation-context")).toContainText("empty/unmatched feature enters open tail")

  await page.getByTestId("view-lineage").click()
  await expect(page.getByTestId("current-view")).toContainText("Lineage")
  await expect(page.getByTestId("right-panel-title")).toContainText("Lineage")
  await expect(page.getByTestId("central-lineage-canvas")).toHaveAttribute("data-projected-relation-count", "5")
  await expect(page.getByTestId("view-lineage")).toHaveAttribute("data-asteria-selected", "true")
  await expect(page.locator(relationIdSelector("relation:lineage:trace-cat"))).toHaveAttribute("data-relation-type", "extends")
  await expect(page.locator(relationIdSelector("relation:lineage:trace-preserve"))).toHaveAttribute("data-relation-type", "preserves")
  await expect(page.locator(".architecture-map-edge")).toHaveCount(5)
  await page.screenshot({ path: path.join(acceptanceDir, "lineage-dark.png"), fullPage: false })

  await page.getByTestId("view-evidence").click()
  await expect(page.getByTestId("current-view")).toContainText("Evidence")
  await expect(page.getByTestId("right-panel-title")).toContainText("Evidence")
  await expect(page.getByTestId("central-evidence-canvas")).toHaveAttribute("data-projected-relation-count", "8")
  await expect(page.getByTestId("view-evidence")).toHaveAttribute("data-asteria-selected", "true")
  await expect(page.locator(relationIdSelector("relation:evidence:proof-tail"))).toHaveAttribute("data-relation-type", "theoretically_supports")
  await expect(page.locator(relationIdSelector("relation:evidence:fixture-response"))).toHaveAttribute("data-relation-type", "validates_implementation")
  await expect(page.locator(relationIdSelector("relation:evidence:finland-pending"))).toHaveAttribute("data-relation-type", "pending")
  await page.screenshot({ path: path.join(acceptanceDir, "evidence-dark.png"), fullPage: false })

  await page.getByTestId("view-architecture").click()
  await page.getByTestId("topbar-toggle-theme").click()
  await expect(page.locator("html")).toHaveAttribute("data-theme", "light")
  await page.mouse.move(600, 170)
  await page.screenshot({ path: path.join(acceptanceDir, "architecture-light.png"), fullPage: false })
})

test("RC6 keyboard model selector and skip paths are reachable before dense graph nodes", async ({ page }) => {
  await page.goto("/")
  await page.keyboard.press("Tab")
  await expect(page.getByText("Skip to canvas")).toBeFocused()
  await page.keyboard.press("Enter")
  await expect(page.getByTestId("architecture-workspace-stage")).toBeFocused()

  await page.getByTestId("topbar-model-selector").focus()
  await expect(page.getByTestId("topbar-model-selector")).toBeFocused()
  await page.keyboard.press("ArrowUp")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-active-model", "original-trace")
  await expect(page.getByTestId("central-model-status")).toContainText("Original TRACE")
  await page.keyboard.press("ArrowDown")
  await expect(page.getByTestId("architecture-workspace-stage")).toHaveAttribute("data-active-model", "cat-trace-frozen-v2")
  await expect(page.getByTestId("central-model-status")).toContainText("CAT-TRACE Frozen V2")

  await page.keyboard.press("Tab")
  await expect(page.getByTestId("topbar-search")).toBeFocused()
})
